spring:
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:jupjup
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

  #Redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false

---

spring:
  profiles: release

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:jupjup
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: update
    show-sql: true
    open-in-view: false

  #Redis
  cache:
    type: redis
  redis:
    host: 10.120.72.245
    port: 6379
  data:
    redis:
      repositories:
        enabled: false