server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  jwt:
    secret: KimdddsIdDidkSidjdpSJd937sdjdfjKJFudDjksdfdfi435k34tjHDKHd8iudsfFHkf8D8fKF9FDkl43ewlsdaf8dsafjk23KDF99dfF8fd6FDjDFasdfkkweqrFkdodkwe49flKd9Fuhsdfklsdaf98sdf98FDS89dfsjkHJK98DS98KFHD

  # Gmail SMTP Server Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: s19066@gsm.hs.kr
    password: iiqrerusxvwowahk
    properties:
      mail:
        smtp:
          timeout: 9999
          auth: true
          starttls:
            enable: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

#AWS
cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-2
    credentials:
      access-key: AKIAUFJW3PBKUF7BZD5I
      secret-key: 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
    stack:
      auto: false

    s3:
      bucket: jupjupapplication
      stack:
        auto: false
      credentials:
        instanceProfile: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error